"""Added roles and user ownership to leads

Revision ID: ff50bcd8a0b3
Revises:
Create Date: 2026-03-15 12:21:19.975950
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff50bcd8a0b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
       # ### commands auto generated by Alembic - please adjust! ###
       with op.batch_alter_table('lead', schema=None) as batch_op:
              batch_op.alter_column(
                     'user_id',
                     existing_type=sa.INTEGER(),
                     nullable=False,
              )
              batch_op.create_foreign_key(
                     'fk_lead_user_id_user',
                     'user',
                     ['user_id'],
                     ['id'],
              )

       with op.batch_alter_table('user', schema=None) as batch_op:
              batch_op.alter_column(
                     'username',
                     existing_type=sa.VARCHAR(length=50),
                     type_=sa.String(length=150),
                     existing_nullable=False,
              )
              batch_op.alter_column(
                     'password',
                     existing_type=sa.VARCHAR(length=255),
                     type_=sa.String(length=150),
                     existing_nullable=False,
              )

       # ### end Alembic commands ###


def downgrade():
       # ### commands auto generated by Alembic - please adjust! ###
       with op.batch_alter_table('user', schema=None) as batch_op:
              batch_op.alter_column(
                     'password',
                     existing_type=sa.String(length=150),
                     type_=sa.VARCHAR(length=255),
                     existing_nullable=False,
              )
              batch_op.alter_column(
                     'username',
                     existing_type=sa.String(length=150),
                     type_=sa.VARCHAR(length=50),
                     existing_nullable=False,
              )

       with op.batch_alter_table('lead', schema=None) as batch_op:
              batch_op.drop_constraint('fk_lead_user_id_user', type_='foreignkey')
              batch_op.alter_column(
                     'user_id',
                     existing_type=sa.INTEGER(),
                     nullable=True,
              )

       # ### end Alembic commands ###
